server:
  port: 7301
spring:
  devtools:
    restart:
      enabled: false
  security:
    user:
      name: marvin
      password: 123
      roles: admin
logging:
  path: log
  level:
    root: info
    com.example.demo: debug
demo:
  db:
    url: jdbc:mysql://localhost:3306/test
    username: marvin
    password: 123456
  jms:
    url: tcp://localhost:61616
    username: marvin
    password: 123456
  jta:
    enable: false
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-methods: GET,POST
        allowed-origins: http://example.com
