demo:
  db:
    url: jdbc:mysql://192.168.3.42:3306/test?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
  jms:
    url: tcp://192.168.3.42:61616
    username: marvin
    password: 123
  jta:
    enable: false
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-methods: GET,POST
        allowed-origins: http://example.com
logging:
  config: classpath:log4j2.xml
spring:
  data:
    mongodb:
      host: 192.168.3.42
